version: "3.8"
services:
  #######################################
  # OAI-RNIS
  #######################################
  oai-rnis:
    image: oaisoftwarealliance/oai-rnis:latest
    container_name: 'oai-rnis'
    environment:
      CONFIG_FILE: '/usr/local/etc/configuration.yaml'
      RNIS_DESCRIPTOR: '/usr/local/etc/rnis-descriptor.yaml'
      MOUNT_CONFIG: 'no'
      PORT: 80
      LOG_LEVEL: info
      REGISTER_TO_MEP: 'yes'
      MEP_URL: 'http://oai-mep.org/service_registry/v1/register'
      HOST: 192.168.70.169
      CN_HANDLER_IP: 192.168.70.168
      CN_HANDLER_PORT: 80
      RABBITMQ_IP: 192.168.70.166
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: user
      RABBITMQ_PASSWORD: password
    healthcheck:
      test: /bin/sh -c "pgrep oai_rnis"
      interval: 5s
      timeout: 2s
      retries: 15
    networks:
       public_net:
          ipv4_address: 192.168.70.169
networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net
        ipam:
            config:
                - subnet: 192.168.70.0/24
        driver_opts:
            com.docker.network.bridge.name: "demo-oai"
